I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1764, in script
    if bryan_study_group == True:
  File "game/script.rpy", line 1764, in <module>
    if bryan_study_group == True:
NameError: name 'bryan_study_group' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1764, in script
    if bryan_study_group == True:
  File "C:\Users\tamim\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 1842, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\tamim\Downloads\renpy-8.2.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\tamim\Downloads\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1764, in <module>
    if bryan_study_group == True:
NameError: name 'bryan_study_group' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
InteractiveNovel 1.0
Mon Jul 29 21:53:21 2024
